# Generated by Django 5.2.5 on 2025-08-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annupurna_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='institue',
            new_name='institution',
        ),
    ]
